services:
  target:
    build: ./target
    ports:
      - "8080:80"
    networks: [testnet]

  agent:
    build: ./agent
    environment:
      - TARGET_HOST=target
      - TARGET_USER=root
      - TARGET_PASS=rootpass
      - TARGET_SSH_PORT=22
    volumes:
      - ./reports/allure-results:/reports/allure-results
    networks: [testnet]

  allure:
    image: frankescobar/allure-docker-service:latest
    ports:
      - "5050:5050"
    volumes:
      - ./reports/allure-results:/app/allure-results
      - ./reports/allure-report:/app/default-reports
    networks: [testnet]

networks:
  testnet:
    driver: bridge
